// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using msih.p4g.Server.Features.Base.ProfileService.Data;

#nullable disable

namespace msih.p4g.Server.Features.Base.ProfileService.Data.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    partial class ProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("msih.p4g.Server.Features.Base.ProfileService.Model.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConsentReceiveEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConsentReceiveMail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConsentReceiveText")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UnsubscribeEmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UnsubscribeMail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UnsubscribeMobile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("msih.p4g.Server.Features.Base.ProfileService.Model.Profile", b =>
                {
                    b.OwnsOne("msih.p4g.Server.Features.Base.ProfileService.Model.AddressModel", "Address", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ModifiedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
