// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace msih.p4g.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Intentionally left blank or can be deleted.
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally left blank or can be deleted.
        }
    }
}
