// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace msih.p4g.Migrations
{
    partial class InitialCreate
    {
        // Intentionally left blank or can be deleted.
    }
}
