// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using msih.p4g.Server.Common.Data;

#nullable disable

namespace msih.p4g.Server.Common.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250112140000_MoveSuspensionFieldsToFundraiser")]
    partial class MoveSuspensionFieldsToFundraiser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This would normally contain the full model definition
            // For this migration, we're focusing on the schema changes
            // The model will be properly generated when the migration is applied
        }
    }
}